package com.indialives;

public interface SetAttributeConstants {
	String AUTH_ERROR_MSG = "AUTH_ERROR_MSG";
	String COMMUNITY_LIST="COMMUNITY_LIST";
	String PROPERTY_LIST="PROPERTY_LIST";
	String PROPERTY_ENUM_LIST = "PROPERTY_ENUM_LIST";
	String PROPERTY_OBJ="PROPERTY_OBJ";
	String PROPERTY_NAME_LIST="PROPERTY_NAME_LIST";
	String COMPLAINT_TYPE_LIST="COMPLAINT_TYPE_LIST";
	String SEVERITY_TYPE_LIST="SEVERITY_TYPE_LIST";	
	String COMMUNITY_ID="COMMUNITY_ID";
	String GET_COMPLAINTS_LIST="GET_COMPLAINTS_LIST";
	
}
