DROP DATABASE IF EXISTS INDIALIVES;
CREATE DATABASE INDIALIVES;
USE INDIALIVES;

CREATE TABLE `ROLES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PRIVILEGES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `CITIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `STATES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `COUNTRIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `COMMUNITIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(300) NOT NULL,
  `CITY` INT(10) UNSIGNED NOT NULL,
  `STATE` INT(10) UNSIGNED NOT NULL,
  `COUNTRY` INT(10) UNSIGNED NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `ROLE_PRIVILEGES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INT(10) UNSIGNED NOT NULL,
  `PRIVILEGE_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `USERS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMMUNITY_ID` INT(10) UNSIGNED NOT NULL,
  `EMAIL_ID` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `MOBILE_NO` VARCHAR(12) NOT NULL,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  `ROLE_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;