INSERT INTO AMENITY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Amenity1","Amenity1");
INSERT INTO AMENITY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Amenity2","Amenity2");
INSERT INTO AMENITY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Amenity3","Amenity3");


INSERT INTO AD_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Adboard1","Adboard1");
INSERT INTO AD_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Adboard1","Adboard1");
INSERT INTO AD_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Adboard1","Adboard1");


INSERT INTO COMPLAINT_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Complaint1","Complaint1");
INSERT INTO COMPLAINT_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Complaint2","Complaint2");
INSERT INTO COMPLAINT_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Complaint3","Complaint3");


INSERT INTO NOTICE_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Notice1","Notice1");
INSERT INTO NOTICE_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Notice2","Notice2");
INSERT INTO NOTICE_BOARD_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Notice3","Notice3");


INSERT INTO PROPERTY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Property1","Property1");
INSERT INTO PROPERTY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Property2","Property2");
INSERT INTO PROPERTY_TYPE_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Property3","Property3");


INSERT INTO SEVERITY_ENUM (ID,NAME,DESCRIPTION) VALUES (1,"Severity1","Severity1");
INSERT INTO SEVERITY_ENUM (ID,NAME,DESCRIPTION) VALUES (2,"Severity2","Severity2");
INSERT INTO SEVERITY_ENUM (ID,NAME,DESCRIPTION) VALUES (3,"Severity3","Severity3");

INSERT INTO USERS(ID,EMAIL_ID,PASSWORD,MOBILE_NO,FIRST_NAME,LAST_NAME) VALUES (1,"test@test.com","test","9916958269","test","test");	







