DROP DATABASE IF EXISTS INDIALIVES;
CREATE DATABASE INDIALIVES;
USE INDIALIVES;

DROP TABLE IF EXISTS `ROLES`;
CREATE TABLE `ROLES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PRIVILEGES`;
CREATE TABLE `PRIVILEGES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `CITIES`;
CREATE TABLE `CITIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `STATES`;
CREATE TABLE `STATES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `COUNTRIES`;
CREATE TABLE `COUNTRIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `COMMUNITIES`;
CREATE TABLE `COMMUNITIES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(300) NOT NULL,
  `CITY` INT(10) UNSIGNED NOT NULL,
  `STATE` INT(10) UNSIGNED NOT NULL,
  `COUNTRY` INT(10) UNSIGNED NOT NULL,
  `PIN_CODE` VARCHAR(10) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK_COMMUNITIES_1` (`CITY`),
  KEY `FK_COMMUNITIES_2` (`STATE`),
  KEY `FK_COMMUNITIES_3` (`COUNTRY`),
  CONSTRAINT `FK_COMMUNITIES_1` FOREIGN KEY (`CITY`) REFERENCES `CITIES` (`ID`),
  CONSTRAINT `FK_COMMUNITIES_2` FOREIGN KEY (`STATE`) REFERENCES `STATES` (`ID`),
  CONSTRAINT `FK_COMMUNITIES_3` FOREIGN KEY (`COUNTRY`) REFERENCES `COUNTRIES` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `ROLE_PRIVILEGES`;
CREATE TABLE `ROLE_PRIVILEGES` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INT(10) UNSIGNED NOT NULL,
  `PRIVILEGE_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK_ROLE_PRIVILEGES_1` (`ROLE_ID`),
  KEY `FK_ROLE_PRIVILEGES_2` (`PRIVILEGE_ID`),
  CONSTRAINT `FK_ROLE_PRIVILEGES_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ID`),
  CONSTRAINT `FK_ROLE_PRIVILEGES_2` FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `PRIVILEGES` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMMUNITY_ID` INT(10) UNSIGNED NOT NULL,
  `EMAIL_ID` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `MOBILE_NO` VARCHAR(12) NOT NULL,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  `ROLE_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK_USERS_1` (`COMMUNITY_ID`),
  KEY `FK_USERS_2` (`ROLE_ID`),
  CONSTRAINT `FK_USERS_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ID`),
  CONSTRAINT `FK_USERS_1` FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;