USE indialives;
ALTER TABLE ROLE_PRIVILEGES
ADD CONSTRAINT `FK_ROLE_PRIVILEGES_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ID`),
ADD CONSTRAINT `FK_ROLE_PRIVILEGES_2` FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `PRIVILEGES` (`ID`);

ALTER TABLE COMMUNITIES ADD CONSTRAINT `FK_COMMUNITIES_1` FOREIGN KEY (`CITY`) REFERENCES `CITIES` (`ID`),
ADD CONSTRAINT `FK_COMMUNITIES_2` FOREIGN KEY (`STATE`) REFERENCES `STATES` (`ID`),
ADD CONSTRAINT `FK_COMMUNITIES_3` FOREIGN KEY (`COUNTRY`) REFERENCES `COUNTRIES` (`ID`);

ALTER TABLE USERS
ADD CONSTRAINT `FK_USERS_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ID`),
ADD CONSTRAINT `FK_USERS_1` FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITIES` (`ID`);