package com.indialives;

public interface ApplicationConstants {
	String INVALID_USER = "INVALID_USER";
	String FILE_TYPE_NAME="Filedata";
	String UPLOAD_FLAT_COLUMN_NAME_ORDER="UPLOAD_FLAT_COLUMN_NAME_ORDER";
	String UPLOAD_VILLA_COLUMN_NAME_ORDER="UPLOAD_VILLA_COLUMN_NAME_ORDER";
	String UPLOAD_PARKING_COLUMN_NAME_ORDER="UPLOAD_PARKING_COLUMN_NAME_ORDER";
	String UPLOAD_PROPERTY_OWNER_COLUMN_NAME_ORDER="UPLOAD_PROPERTY_OWNER_COLUMN_NAME_ORDER";
	
}
