package com.indialives;

public interface SQLConstants {
	String FIND_VALID_USER="FIND_VALID_USER";
	String GET_USER_COMMUNITIES="GET_USER_COMMUNITIES";
	String GET_PROPERTIES_LIST="GET_PROPERTIES_LIST";
	String FLAT_PROPERTIES_INFO="FLAT_PROPERTIES_INFO";
	String VILLA_PROPERTIES_INFO="VILLA_PROPERTIES_INFO";
	String PARKING_PROPERTIES_INFO="PARKING_PROPERTIES_INFO";
	String ADD_COMPLAINTS="ADD_COMPLAINTS";
	String GET_PROPERTY_ENUM_LIST="GET_PROPERTY_ENUM_LIST";
	String GET_PROPERTIES__NAME_LIST="GET_PROPERTIES__NAME_LIST";
	String GET_COMPLAINT__TYPE_LIST="GET_COMPLAINT__TYPE_LIST";
	String GET_SEVERITY__TYPE_LIST="GET_SEVERITY__TYPE_LIST";
	String GET_COMPLIANTS_LIST="GET_COMPLIANTS_LIST";
}
