package com.indialives;

public interface SQLConstants {
	String FIND_VALID_USER="FIND_VALID_USER";
	String GET_USER_COMMUNITIES="GET_USER_COMMUNITIES";
	String GET_PROPERTIES_LIST="GET_PROPERTIES_LIST";
	String FLAT_PROPERTIES_INFO="FLAT_PROPERTIES_INFO";
	String VILLA_PROPERTIES_INFO="VILLA_PROPERTIES_INFO";
	String PARKING_PROPERTIES_INFO="PARKING_PROPERTIES_INFO";
	String ADD_COMPLAINTS="ADD_COMPLAINTS";
	String GET_PROPERTY_ENUM_LIST="GET_PROPERTY_ENUM_LIST";
	String GET_PROPERTIES__NAME_LIST="GET_PROPERTIES__NAME_LIST";
	String GET_COMPLAINT__TYPE_LIST="GET_COMPLAINT__TYPE_LIST";
	String GET_SEVERITY__TYPE_LIST="GET_SEVERITY__TYPE_LIST";
	String GET_COMPLIANTS_LIST="GET_COMPLIANTS_LIST";
	String GET_COMPLIANTS_LIST_BY_ADMIN="GET_COMPLIANTS_LIST_BY_ADMIN";
	String GET_ROLE_PRIVILEGS_LIST="GET_ROLE_PRIVILEGS_LIST";
	String GET_FLAT_LIST="GET_FLAT_LIST";
	String GET_VILLA_LIST="GET_VILLA_LIST";
	String GET_FLAT__TYPE_LIST="GET_FLAT__TYPE_LIST";
	String GET_VILLA_LIST_FOR_ADMIN="GET_VILLA_LIST_FOR_ADMIN";
	String GET_BLOCK_LIST="GET_BLOCK_LIST";
	String ADD_FLAT="ADD_FLAT";
	String ADD_VILLA="ADD_VILLA";
	String ADD_BLOCK="ADD_BLOCK";
}
